#!/bin/bash

IMAGE_NAME=jiulongw/aosp-lollipop
CONTAINER_NAME=aosp-lollipop
AOSP_SRC_HOST=~/aosp
AOSP_SRC_DEST=/home/android/aosp

if [ ! "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
  if [ "$(docker ps -aq -f status=exited -f name=$CONTAINER_NAME)" ]; then
    docker start -ia $CONTAINER_NAME
  else
    docker run -it --name $CONTAINER_NAME -v $AOSP_SRC_HOST:$AOSP_SRC_DEST $IMAGE_NAME /bin/bash
  fi
else
  docker exec -it $CONTAINER_NAME /bin/bash
fi
